config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :cities do
    resources :places, only: [:new, :create, :edit, :index]
    resources :activities, only: [:new, :create, :edit, :update]
  end

  resources :trips do
    resources :activities, only: [:index]
  end

  resources :places do
    resources :trips, only: [:new, :create]
  end

  resources :appointments
  resources :places, only: [:edit, :update]
  resources :cities
  resources :pets

  resources :activities, only: :show do
    resources :meetings, only: [:create]
  end

  get "my_trips", to: "trips#my_trips_index", as: "my_trips"

   # Sidekiq Web UI, only for admins.
   require "sidekiq/web"
   authenticate :user, ->(user) { user.admin? } do
     mount Sidekiq::Web => '/sidekiq'
   end

end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user

  validates :size, presence: true
  validates :breed, presence: true
  validates :details, presence: true
  validates :photo, presence: true
  validates :age, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :name, presence: true

  has_one_attached :photo
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController


  def index
    @pets = current_user.pets
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user

    if @pet.save!
      redirect_to pets_path, notice: 'Pet was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    if @pet.save!
      redirect_to pets_path,  notice: 'Pet was successfully edited.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :age, :size, :breed, :details, :user_id, :photo)
  end
end

app/views/pets/edit.html.erb
<div class="container_form mt-5 ">
  <div class="container mt-3">
    <p><strong>Edit Pet</strong></p>

    <%= simple_form_for(@pet) do |form| %>

      <div class="form-actions">
        <%= form.input :name %>
        <%= form.input :age %>
        <%= form.input :size %>
        <%= form.input :breed %>
        <%= form.input :details %>
        <%= form.input :photo, as: :file %>

        <%= form.button :submit, 'Update', class: 'btn-donate' %>
        <%= button_tag 'Back', class: 'btn', role: 'button', style: 'text-decoration: none', onclick: 'javascript:history.back();' %>
      </div>
    <% end %>

  </div>
</div>

<br>
<br>

app/views/pets/index.html.erb
<style>
#colorful {
   width: 31.4px;
   height: 31.4px;
   border-radius: 50%;
   background: #2ed3ff;
   transform-origin: top;
   display: grid;
   animation: colorful-3vgb5t 1s infinite linear;
}

#colorful::before,
#colorful::after {
   content: "";
   grid-area: 1/1;
   background: #619eff;
   border-radius: 50%;
   transform-origin: top;
   animation: inherit;
   animation-name: colorful-k94uub;
}

#colorful::after {
   background: #474bff;
   --s: 180deg;
}

@keyframes colorful-3vgb5t {
   0%, 20% {
      transform: rotate(0);
   }

   100% {
      transform: rotate(360deg);
   }
}

@keyframes colorful-k94uub {
   50% {
      transform: rotate(var(--s,90deg));
   }

   100% {
      transform: rotate(0);
   }
}

#content {
      display: none;
    }

.container-map {
    overflow: hidden; /* Evita que o mapa ultrapasse os limites do contêiner */
  }

</style>

<center><div id="colorful" style="margin-top: 450px;"></div></center>

<div id="content">

<div class="container mt-5">
  <h1 class="mt-15"><strong>Your Pets</strong></h1>
</div>

<div class="container mt-3">
  <%= link_to "Add Pet", new_pet_path, class:"btn-donate mt-5"%>
</div>

<div class="cards-container">
  <% @pets.each do |pet| %>
    <div class="card">
        <% if pet.photo.attached? %>
          <%= image_tag cl_image_path(pet.photo.key), class: "card-image", alt: "Pet Image" %>
        <% end %>
      <div class="card-details">
    </div>

    <button class="card-button">
      <%= link_to pet.name, pet, class: "pet-name" %>
    </button>
  </div>

    <% end %>
</div>



<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<script>
  function initializeMap() {
    // Inicialize o mapa aqui
    // Certifique-se de que o contêiner do mapa tem uma altura definida corretamente
  }

  // Simule o carregamento por 6 segundos (substitua isso pela sua lógica real de carregamento)
  setTimeout(function() {
    // Oculte o dot de carregamento
    document.getElementById('colorful').style.display = 'none';

    // Mostre o conteúdo
    document.getElementById('content').style.display = 'block';

    // Dispare um evento de redimensionamento do mapa
    window.dispatchEvent(new Event('resize'));
  }, 2000); // Simulando um tempo de carregamento de 3 segundos
</script>

app/views/pets/new.html.erb
<div class="container_form mt-5 ">

    <div class="container ml-5 p-1">
      <h2><i class="fa-solid fa-dog"></i>   <strong>New Pet</strong></h2>
    </div>

      <%= simple_form_for(@pet) do |form| %>

        <div class="form-actions">
          <%= form.input :name %>
          <%= form.input :age %>
          <%= form.input :size %>
          <%= form.input :breed %>
          <%= form.input :details %>
          <%= form.input :photo, as: :file %>

          <%= button_tag 'Create Pet', type: 'submit', class: 'btn-donate mt-0' %>
          <%= button_tag 'Back', class: 'btn', role: 'button', style: 'text-decoration: none', onclick: 'javascript:history.back();' %>
        </div>
      <% end %>

</div>

<br>
<br>

app/views/pets/show.html.erb
<div class="container_pet mt-5">
  <div class="container">
    <div class="row">
      <!-- Left Column for Pet Image -->
      <div class="col-md-5">
        <%= cl_image_tag(@pet.photo.key, height: 300, width: 400, crop: :fill, style: "border: 2px solid #c3c6ce; border-radius: 90px 30px;") if @pet.photo.attached? %>

      </div>

      <!-- Right Column for Card and Buttons -->
      <div class="col-md-7">
            <div style="margin-top: 15px">
              <h2><strong><%= @pet.name %></strong></h2>
              <p><strong>Age:</strong> <%= @pet.age %></p>
              <p><strong>Size:</strong> <%= @pet.size %></p>
              <p><strong>Breed:</strong> <%= @pet.breed %></p>
              <p><strong>Details:</strong> <%= @pet.details %></p>
            </div>

              <div style="margin-top: 26px;">
                <%= link_to "Edit Pet", edit_pet_path(@pet), class: "btn-donate" %>
                <%= button_tag 'Back', class: 'btn', role: 'button', style: 'text-decoration: none', onclick: 'javascript:history.back();' %>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>