config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :cities do
    resources :places, only: [:new, :create, :edit, :index]
    resources :activities, only: [:new, :create, :edit, :update]
  end

  resources :trips do
    resources :activities, only: [:index]
  end

  resources :places do
    resources :trips, only: [:new, :create]
  end

  resources :appointments
  resources :places, only: [:edit, :update]
  resources :cities
  resources :pets

  resources :activities, only: :show do
    resources :meetings, only: [:create]
  end

  get "my_trips", to: "trips#my_trips_index", as: "my_trips"

   # Sidekiq Web UI, only for admins.
   require "sidekiq/web"
   authenticate :user, ->(user) { user.admin? } do
     mount Sidekiq::Web => '/sidekiq'
   end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div>
    <p>&copy; <%= Time.now.year %> • Pets Out® • All rights reserved.</p>
    <i class="fab fa-facebook"></i>
    <i class="fab fa-linkedin"></i>
    <i class="fab fa-instagram"></i>
    <i class="fab fa-youtube"></i>
    <i class="fab fa-github"></i>
    <i class="fab fa-twitter"></i>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://static.vecteezy.com/ti/vetor-gratis/t2/9551676-timido-cao-logo-ilustracao-representando-cao-timido-adequado-para-empresa-de-animais-gratis-vetor.jpg", style: "height: 50px; width: auto;" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <%# <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link"  </li> %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://media.licdn.com/dms/image/C4E03AQFSJ8r0MlqIaQ/profile-displayphoto-shrink_800_800/0/1615926336606?e=1706140800&v=beta&t=hEWfDhMbwZcCq5loKK36B03eeKPtA8-muXjWWoPJYLY", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My trips", my_trips_path, class: "dropdown-item" %>
              <%= link_to "My pets", pets_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>