config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :cities do
    resources :places, only: [:new, :create, :edit, :index]
    resources :activities, only: [:new, :create, :edit, :update]
  end

  resources :trips do
    resources :activities, only: [:index]
  end

  resources :places do
    resources :trips, only: [:new, :create]
  end

  resources :appointments
  resources :places, only: [:edit, :update]
  resources :cities
  resources :pets

  resources :activities, only: :show do
    resources :meetings, only: [:create]
  end

  get "my_trips", to: "trips#my_trips_index", as: "my_trips"

   # Sidekiq Web UI, only for admins.
   require "sidekiq/web"
   authenticate :user, ->(user) { user.admin? } do
     mount Sidekiq::Web => '/sidekiq'
   end

end

app/views/pages/home.html.erb
<style>
#colorful {
   width: 31.4px;
   height: 31.4px;
   border-radius: 50%;
   background: #2ed3ff;
   transform-origin: top;
   display: grid;
   animation: colorful-3vgb5t 1s infinite linear;
}

#colorful::before,
#colorful::after {
   content: "";
   grid-area: 1/1;
   background: #619eff;
   border-radius: 50%;
   transform-origin: top;
   animation: inherit;
   animation-name: colorful-k94uub;
}

#colorful::after {
   background: #474bff;
   --s: 180deg;
}

@keyframes colorful-3vgb5t {
   0%, 20% {
      transform: rotate(0);
   }

   100% {
      transform: rotate(360deg);
   }
}

@keyframes colorful-k94uub {
   50% {
      transform: rotate(var(--s,90deg));
   }

   100% {
      transform: rotate(0);
   }
}

#content {
      display: none;
    }

.container-map {
    overflow: hidden; /* Evita que o mapa ultrapasse os limites do contêiner */
  }

</style>

<center><div id="colorful" style="margin-top: 450px;"></div></center>

<div id="content">

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
  url(https://res.cloudinary.com/dxymj7m5b/image/upload/v1701816504/home_amrjot.jpg);
  background-size: 100%; background-position: center">

  <div class="container">
    <h1>Pets Out! </h1>
    <p>Travel assistant for amazing trips with your pets</p>
    <div class="col-sm-8 my-3">
      <%= form_with url: root_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
                            params[:query],
                            class: "form-control",
                            placeholder: "Type a city to visit with your pet!"
        %>
        <%= submit_tag "Search", name: "", class: "btn-donate text-align: center;" %>
      <% end %>
    </div>
  </div>
</div>

 <%# <%= link_to "Add city", new_city_path, class: "btn-donate" %>

<div class="container_cities mt-5">
  <h1>Popular pet-friendly <strong>cities</strong> </h1>

  <div class="parent" p-5 >
      <% if @city.present? %>
    <div class="card-trip mt-2">
      <%= cl_image_tag @city.photo.key, height: 400, width: 500, crop: :fill if @city.photo.attached? %>

      <div class="card-trip-infos">
        <div>
          <h2> <%= link_to @city.local, city_places_path(@city.id) %></h2>
        </div>
      </div>
    </div>

    <% else %>
      <% @cities.first(12).each do |city| %>
      <div class="card-trip mt-2">
        <%= cl_image_tag city.photo.key, height: 400, width: 500, crop: :fill if city.photo.attached? %>

        <div class="card-trip-infos">
          <div>
          <h2> <%= link_to city.local, city_places_path(city.id) %> </h2>
          </div>
        </div>
      </div>
        <% end %>
      <% end %>
  </div>
</div>

<div class="container_activities">
      <h1>Most upvoted <strong>activities</strong></h1>
  <div class="parent" p-5 >
        <% @activities.first(12).each do |a| %>
        <div class="card-product mt-2">
          <%= cl_image_tag a.photo.key, height: 400, width: 500, crop: :fill if a.photo.attached? %>

          <div class="card-product-infos">
            <h2><%= a.title %></h2>
            <p><%= a.details %></p>
            <p><strong>in <%= a.city.local %></strong></p>
          </div>
        </div>
        <% end %>
  </div>
</div>

<script>
  function initializeMap() {
    // Inicialize o mapa aqui
    // Certifique-se de que o contêiner do mapa tem uma altura definida corretamente
  }

  // Simule o carregamento por 6 segundos (substitua isso pela sua lógica real de carregamento)
  setTimeout(function() {
    // Oculte o dot de carregamento
    document.getElementById('colorful').style.display = 'none';

    // Mostre o conteúdo
    document.getElementById('content').style.display = 'block';

    // Dispare um evento de redimensionamento do mapa
    window.dispatchEvent(new Event('resize'));
  }, 2000); // Simulando um tempo de carregamento de 3 segundos
</script>
<!-- app/views/shared/_footer.html.erb -->