config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :cities do
    resources :places, only: [:new, :create, :edit, :index]
    resources :activities, only: [:new, :create, :edit, :update]
  end

  resources :trips do
    resources :activities, only: [:index]
  end

  resources :places do
    resources :trips, only: [:new, :create]
  end

  resources :appointments
  resources :places, only: [:edit, :update]
  resources :cities
  resources :pets

  resources :activities, only: :show do
    resources :meetings, only: [:create]
  end

  get "my_trips", to: "trips#my_trips_index", as: "my_trips"

   # Sidekiq Web UI, only for admins.
   require "sidekiq/web"
   authenticate :user, ->(user) { user.admin? } do
     mount Sidekiq::Web => '/sidekiq'
   end

end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  belongs_to :city

  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :title, presence: true, uniqueness: true
  validates :subtitle, presence: true
  validates :address, presence: true
  validates :pricing, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :rooms, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :details, presence: true
  validates :photo, presence: true

  has_many :trips
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @city = City.find(params[:city_id])
    @places = @city.places
    @trip = Trip.new

    @markers = @places.geocoded.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {place: place}),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def new
    @place = Place.new
    @city = City.find(params[:city_id])
  end

  def create
    @city = City.find(params[:city_id])
    @place = Place.new(place_params)
    @place.city = @city
    @place.user = current_user
    if @place.save
      redirect_to city_places_path(@city)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    if @place.update(place_params)
      redirect_to city_places_path(@place.city)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def place_params
    params.require(:place).permit(:title, :subtitle, :address, :pricing, :rooms, :details, :city_id, :photo)
  end
end

app/views/places/_info_window.html.erb
<div class="container">
  <%= cl_image_tag place.photo.key, height: 100, width: 125, crop: :fill if place.photo.attached? %>
  <h2> <%= place.title %> </h2>
  <p> <%= place.address %> </p>
  <p> <strong> £ <%= place.pricing %> </strong></p>
  <%# <div class="card-places-btn">
          <%= link_to "Book this place!", new_trip_path(place_id: place.id), class:"btn btn-primary m-3" %>
        <%# </div> %>

  <%= link_to "Book this place", new_trip_path(place_id: place.id), class:"btn-donate" %>
  </div>

app/views/places/_marker.html.erb
<%= image_tag "https://static.vecteezy.com/ti/vetor-gratis/t2/9551676-timido-cao-logo-ilustracao-representando-cao-timido-adequado-para-empresa-de-animais-gratis-vetor.jpg", height: 30, width: 30, alt: "Logo" %>

app/views/places/edit.html.erb
<div class="container mt-3">
  <p><strong>Edit Place</strong></p>

  <%= simple_form_for(@place) do |form| %>

    <div class="form-actions">
      <%= form.input :title %>
      <%= form.input :subtitle %>
      <%= form.input :address %>
      <%= form.input :pricing %>
      <%= form.input :rooms %>
      <%= form.input :details %>
      <%= form.input :photo, as: :file %>


    <%# <div class="form-group">
      <label for="photos">Photos:</label>
      <input type="file" name="photos[]" multiple id="photos" class="form-control">
    </div> %>

      <%= form.button :submit, 'Update Place', class: 'btn-donate' %>
    </div>
  <% end %>

app/views/places/index.html.erb
<style>
#colorful {
   width: 31.4px;
   height: 31.4px;
   border-radius: 50%;
   background: #2ed3ff;
   transform-origin: top;
   display: grid;
   animation: colorful-3vgb5t 1s infinite linear;
}

#colorful::before,
#colorful::after {
   content: "";
   grid-area: 1/1;
   background: #619eff;
   border-radius: 50%;
   transform-origin: top;
   animation: inherit;
   animation-name: colorful-k94uub;
}

#colorful::after {
   background: #474bff;
   --s: 180deg;
}

@keyframes colorful-3vgb5t {
   0%, 20% {
      transform: rotate(0);
   }

   100% {
      transform: rotate(360deg);
   }
}

@keyframes colorful-k94uub {
   50% {
      transform: rotate(var(--s,90deg));
   }

   100% {
      transform: rotate(0);
   }
}

#content {
      display: none;
    }

.container-map {
    overflow: hidden; /* Evita que o mapa ultrapasse os limites do contêiner */
  }

</style>

<center><div id="colorful" style="margin-top: 450px;"></div></center>

<div id="content">

  <div style="margin: 15px;">
    <h1>Houses in <strong><%= @city.local %></strong></h1>
  </div>

  <div style="display: grid; grid-template-columns: 2fr 1fr; gap: 0px 10px;">

    <!-- Coluna Esquerda (Places) -->
  <div style="width: 80%;">
    <% @places.each_slice(3) do |places_chunk| %>
      <div style="display: flex; gap: 1px; margin-bottom: 5px;">
        <% places_chunk.each do |place| %>
          <div class="card-places" style="flex: 1; margin-top: 10px; display: flex; flex-direction: column; position: relative;">
            <%= cl_image_tag place.photo.key, height: 400, width: 500, crop: :fill if place.photo.attached? %>

            <div class="card-places-infos p-3" style="margin-bottom: 20px;">
              <div class="card-places-text">
                <h2> <%=  place.title %> </h2>
                <p>  <%=  place.subtitle %> </p>
                <p>  Address: <%=  place.address %> </p>
                <p>  Rooms: <%=  place.rooms %> </p>
                <h2 class="card-places-pricing mt-2"> £ <%=  place.pricing %> </h2>
              </div>
            </div>


            <div class="card-places-btn mt-auto mb-4 m-2">
              <%= link_to "Book this place", new_trip_path(place_id: place.id), class:"btn-donate m-10" %>
            </div>
            </div>

            <% end %>
      </div>
    <% end %>
</div>

    <!-- Coluna Direita (Mapa) -->
    <div class="container-map" style="height: calc(70vh - 100px); margin-top: 10px; margin-right: 20px; width: 45%;">
      <div style="height: 100%;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<script>
  function initializeMap() {
    // Inicialize o mapa aqui
    // Certifique-se de que o contêiner do mapa tem uma altura definida corretamente
  }

  // Simule o carregamento por 6 segundos (substitua isso pela sua lógica real de carregamento)
  setTimeout(function() {
    // Oculte o dot de carregamento
    document.getElementById('colorful').style.display = 'none';

    // Mostre o conteúdo
    document.getElementById('content').style.display = 'block';

    // Inicialize o mapa após o conteúdo ser exibido
    initializeMap();

    // Dispare um evento de redimensionamento do mapa
    window.dispatchEvent(new Event('resize'));
  }, 2000); // Simulando um tempo de carregamento de 3 segundos
</script>

app/views/places/new.html.erb
<div class="container mt-3">
  <p><strong>New Place</strong></p>

  <%= simple_form_for([@city, @place]) do |form| %>

    <div class="form-group">
      <%= form.input :title %>
      <%= form.input :subtitle %>
      <%= form.input :address %>
      <%= form.input :pricing %>
      <%= form.input :rooms %>
      <%= form.input :details %>
      <%= form.input :photo, as: :file %>

      </div>

      <div class="form-actions">
        <%= form.button :submit, 'Create Place', class: 'btn-donate' %>

      </div>
  <% end %>

  <%# <%= link_to 'Back', root, class: 'btn btn-secondary mt-2' %>
</div>